apiVersion: apps/v1
kind: Deployment
metadata:
  name: ron-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ronapp
  template:
    metadata:
      labels:
        app: ronapp
    spec:
      containers:
      - name: ron-container
        image: rggomez10/myap33:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ronapp-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: ronapp 
