# Workflow to deploy the artifacts
name: cd
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  build:
    runs-on: rongo
    environment: prod
    steps:
      - uses: actions/checkout@4.1.1
      - name: Deployment using kubernetes
        run: |
          kubectl apply -f deployment.yml
          kubectl get deployments
